### ISSUE TITLE
Needs complete import  for latest support Windows MixedReality Headsets

### ISSUE THREAD

**Issue by jimshalo10** [mtaulty/Butterflies#1]
Where is complete Room  Unity Package. Searching Unity Asset store does *not* exist

**Comment by jimshalo10** [comment]
There is a lack of complete Butterflies-2017_2_f3mrtp3master.unitypackage, which is too big for GitHub
The Rooms.unity package described does not exist. If possible add all non-toolkit *.unitypackages to this distribution

**Comment by mtaulty** [comment]
I added the room and butterfly unitypackage, not sure if that's going to address the issue here but let me know.

**Comment by jimshalo10** [comment]
That's fixed now works in WMR Headset
