### ISSUE TITLE
Getting Assertion failed: Assertion failed on expression: 'device.IsInsideFrame()

### ISSUE THREAD

**Issue by jimshalo10** [mtaulty/Butterflies#2]
When trying to run/play the app Unity 2017.2.0f3-MRTP3 is complaining about some code added to test something, could the assertion be remove as this is crashing the app

There is not a line number or file name, just came back to Unity after a year away, no idea what this is doing

**Comment by mtaulty** [comment]
I'm not sure either - worth saying that I had these bits in Unity 2017.2.0f3 rather than any MRTP bits.

**Comment by jimshalo10** [comment]
Oh Thanks that explains why nothing appear in my HP MR headset.
Will work on updating the package to support HP WMR Headset
May take a while as have been in Unreal 4 for a year!

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jimshalo10** [comment]
Unity 2017.2.0f3-MRTP3 is corrupt no UWP SUPPORT? Installed  2017.2.0f3 without error
